name: cms

services:
  database:
    container_name: database
    image: postgis/postgis:15-master
    volumes:
      - directus_postgres_data:/var/lib/postgresql/data
      - directus_postgres_backup:/var/lib/postgresql/backup
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U application"]
      interval: 1s
      timeout: 1s
      retries: 30
    environment:
      POSTGRES_USER: 'application'
      POSTGRES_PASSWORD: 'application'
      POSTGRES_DB: 'application'

  cache:
    container_name: cache
    image: redis:6
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 30

  directus:
    container_name: directus
    build: .
    platform: linux/amd64
    ports:
      - 8055:8055
    volumes:
      - directus_upload_data:/directus/uploads
      - ./schema:/directus/schema
      - directus_extensions_data:/directus/extensions
      - directus_logs_data:/directus/logs
    depends_on:
      database:
        condition: service_healthy
      mailhog:
        condition: service_started
      cache:
        condition: service_healthy
    environment:
      KEY: 'change-me-in-production-255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: 'change-me-in-production-6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'application'
      DB_USER: 'application'
      DB_PASSWORD: 'application'

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      LOG_LEVEL: 'warn'

      # you should change this and add 2fa in a production environment.
      ADMIN_EMAIL: 'admin@application.com'
      ADMIN_PASSWORD: 'application'

      EMAIL_FROM: "info@application.com"
      EMAIL_SMTP_HOST: "mailhog"
      EMAIL_SMTP_PORT: "1025"
      EMAIL_TRANSPORT: "smtp"

    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8055/admin || exit 1
      interval: 10s
      timeout: 1s
      retries: 30
      start_period: 1s

  mailhog:
    container_name: mailhog
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'

volumes:
  directus_postgres_data:
    driver: local
  directus_postgres_backup:
    driver: local
  directus_upload_data:
    driver: local
  directus_extensions_data:
    driver: local
  directus_logs_data:
    driver: local